name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-greeting
        run: |
          echo "Hello World!!"
          echo "This is my first Workflow"
      - name: print-goodbye
        run: |
          echo "Thank You"
          echo "Good bye!!"
